[package]
name = "logline-timeline"
version = "0.1.0"
edition = "2021"
description = "Timeline microservice for the LogLine platform"
authors = ["LogLine Team"]
license = "MIT"

[dependencies]
axum = { version = "0.7", features = ["ws", "json"] }
tokio = { version = "1.34", features = ["macros", "rt-multi-thread", "signal"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["serde", "v4"] }
thiserror = "1.0"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
logline-core = { path = "../logline-core" }
logline-protocol = { path = "../logline-protocol" }
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio", "postgres", "uuid", "chrono", "json", "macros", "migrate"] }
hyper = "1.4"

[dev-dependencies]
tokio = { version = "1.34", features = ["macros", "rt", "rt-multi-thread"] }
pg-embed = { version = "0.7.1", default-features = false, features = ["rt_tokio"] }
anyhow = "1.0"
tempfile = "3.10"
portpicker = "0.1"
tower = { version = "0.4", features = ["util"] }
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
http-body-util = "0.1"
